name: iOS starter workflow

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-14

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
      - name: Download libbox
        run: |
          wget https://github.com/xunmod/sing-box-lib/releases/download/1.10.1/Libbox.xcframework.zip
          unzip Libbox.xcframework.zip
          rm Libbox.xcframework.zip
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
      - name: Build
        run: xcodebuild -project sing-box.xcodeproj -scheme SFI -sdk iphoneos archive -archivePath ./archive CODE_SIGNING_REQUIRED=NO AD_HOC_CODE_SIGNING_ALLOWED=YES CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=WTFIMFILLINGHERE ORG_IDENTIFIER=com.xunmod
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: archive.xcarchive/Products/Applications
